services:
  nextbackend:
    container_name: nextbackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    env_file:
      - .env
    environment:
      SCHEDULER_INTERNAL_URL: http://nextscheduler:9092
      SCHEDULER_SHARED_SECRET: ${SECRET_KEY}
    volumes:
      - ./schedules.json:/app/schedules.json
    networks:
      - nextpanel
    restart: unless-stopped

  nextscheduler:
    container_name: nextscheduler
    build:
      context: ./backend
      dockerfile: Dockerfile.scheduler
    env_file:
      - .env
    environment:
      SCHEDULER_SHARED_SECRET: ${SECRET_KEY}
      SCHEDULES_FILE: /app/schedules.json
    volumes:
      - ./schedules.json:/app/schedules.json
    shm_size: "512mb"
    networks:
      - nextpanel
    restart: unless-stopped

  telegrampooling:
    container_name: telegrampooling
    build:
      context: ./backend/telegrampooling
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - nextpanel
    restart: unless-stopped

  nextfrontend:
    container_name: nextfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - nextpanel
    restart: unless-stopped
    depends_on:
      - nextbackend

  cloudflared:
    container_name: nextcloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiYjNlZTcyZTc4NGVkY2RlNTZkYTA1YzcxMjVmZDM3NzEiLCJ0IjoiZmY1YzdhM2YtYTJlNi00OWE0LWIwNTctMGMwMjg1YmZlMmVkIiwicyI6Ill6TmxOREprTm1RdE5UZzFaaTAwWWpjMkxXSm1OMlF0T1dGa1lqZ3dNVFEyTVRRMyJ9
    networks:
      - nextpanel
    restart: unless-stopped
    depends_on:
      - nextbackend
      - nextfrontend
      - nextscheduler

networks:
  nextpanel:
    name: nextpanel
    driver: bridge
